### PR TITLE
In-browser snippet copying

### PR DESCRIPTION
**Pull request by ramiabraham**
Adds copy functionality using `execCommand(‘copy’)` to directly copy the code snippet to the clipboard.

- Will fallback to `cpt.openSnippetCopy()` on failure.
- Uses `cpt.browserCopyStyles()` to set styles because I couldn’t immediately locate an effective means to manipulate styles via the scss/css alone.
- `wp.a11y.speak` is commented out in two cases in `frontend.js`, as the eslintrc config returns an undef error on `wp`. A custom global/environment handler for `wp` - or a line-level eslint rule is required (or suppression of the error itself).
- Needs a grunt build ( I opted for the courtesy of me _not_ compiling in the PR).

Appearance:

snippet copy example

### CODE REVIEW

**Comment by jtsternberg** [comment]
Hey @ramiabraham, tried testing this, but it never copies to the clipboard. Which browser are you using where this works?

**Comment by ramiabraham** [comment]
@jtsternberg did you compile grunt first?

**Comment by jtsternberg** [comment]
Yah. I think I got it now. Thanks

**Comment by jtsternberg** [comment]
💥  Thank you sir 👑 @ramiabraham

**Comment by ramiabraham** [comment]
@jtsternberg Woot!

**Pull request merged**
